print('hello world') 
print('pycharm')
print('pycharm')
print('pycharm')
print('pycharm')
print('pycharm')
print('pycharm')
print('python')
print('python')
print('python')
print('python')
print('python')
